# Generated by Django 4.1.1 on 2022-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rdoc',
            field=models.FileField(blank=True, upload_to='my_doc'),
        ),
    ]
